version: '3.7'

services:
  foodapp:
    container_name: foodapp
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4000:4000
    environment:
      - CHOKIDAR_USEPOLLING=true
